services:
  - type: web
    name: voicecommunity
    env: node
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        sync: false
      - key: LIVEKIT_API_KEY
        sync: false
      - key: LIVEKIT_API_SECRET
        sync: false
      - key: LIVEKIT_WS_URL
        sync: false
      - key: VITE_YOUTUBE_API_KEY
        sync: false
      - key: VITE_SERVER_URL
        sync: false 